apiVersion: apps/v1
kind: Deployment
metadata:
  name: shivani-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: shivani-app

  template:
    metadata:
      labels:
        app: shivani-app

    spec:
      containers:
      - name: shivani-app

        image: 975050024946.dkr.ecr.us-west-1.amazonaws.com/shivani-capstone:latest

        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10